name: ground_station
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  floor: ^1.5.0
  sqflite: ^2.4.2
  get_it: ^9.1.1
  lottie: ^3.2.1
  fl_chart: ^0.69.0
  csv: ^6.0.0
  file_picker: ^8.1.4
  share_plus: ^10.1.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/animations/satellite.json
    - assets/animations/antenna.json
    - assets/animations/satellite_dish.json
    - assets/sample_habits_import.csv
    - assets/sample_export.json
    - assets/CSV_IMPORT_FORMAT.md
    - assets/satellite_alt_512dp.png
